tl.test=Test Panel
tl.test.buttonTitle=Click on me!
tl.test.summaryTitle=Summary
tl.test.currentAssignee=Current Assignee
tl.test.updateAssignee=Update Assignee
tl.test.currentSummary=Current Summary
tl.test.updateSummary=Update Summary
tl.test.selectUserTitle=Select User...
tl.test.update=Update
tl.button.close=Close
tl.dialog.header=Test Plugin window
tl.validation.selectUser=Please select a User
tl.response.success=Success!
tl.issue.updated.assignee=The Assignee has been updated!
tl.issue.updated.summary=The Summary has been updated!
tl.response.error=Error!